name: Build Zoom Per Map

on:
    workflow_dispatch:

run-name: Build Zoom Per Map.
permissions:
    contents: write
    id-token: write
    attestations: write

jobs:
    build:
        uses: ./.github/workflows/build-mod.yml
        with:
            project_name: "ZoomPerMap"
            create_draft_release: true
