name: Build Into the Game

on:
    workflow_dispatch:

run-name: Build Into the Game.
permissions:
    contents: write
    id-token: write
    attestations: write

jobs:
    build:
        uses: ./.github/workflows/build-mod.yml
        with:
            project_name: "SaveLoadedNotifier"
            create_draft_release: true
