name: Build Smart Cursor

on:
    workflow_dispatch:

run-name: Build Smart Cursor.
permissions:
    contents: write
    id-token: write
    attestations: write

jobs:
    build:
        uses: ./.github/workflows/build-mod.yml
        with:
            project_name: "SmartCursor"
            create_draft_release: true
