name: Build Give Me My Cursor Back

on:
    workflow_dispatch:

run-name: Build Give Me My Cursor Back.
permissions:
    contents: write
    id-token: write
    attestations: write

jobs:
    build:
        uses: ./.github/workflows/build-mod.yml
        with:
            project_name: "GiveMeMyCursorBack"
            create_draft_release: true
