name: Build MEEP

on:
    workflow_dispatch:

run-name: Build MEEP.
permissions:
    contents: write
    id-token: write
    attestations: write

jobs:
    build:
        uses: ./.github/workflows/build-mod.yml
        with:
            project_name: "MappingExtensionsAndExtraProperties"
            create_draft_release: true
