name: Build Carry Your Pet

on:
    workflow_dispatch:

run-name: Build Carry Your Pet.
permissions:
    contents: write
    id-token: write
    attestations: write

jobs:
    build:
        uses: ./.github/workflows/build-mod.yml
        with:
            project_name: "CarryYourPet"
            create_draft_release: true
