name: Build Default Window Size

on:
    workflow_dispatch:

run-name: Build Default Window Size.
permissions:
    contents: write
    id-token: write
    attestations: write

jobs:
    build:
        uses: ./.github/workflows/build-mod.yml
        with:
            project_name: "DefaultWindowSize"
            create_draft_release: true
