name: Build Ex-Joja Farm

on:
    workflow_dispatch:

run-name: Build Ex-Joja Farm.
permissions:
    contents: write
    id-token: write
    attestations: write

jobs:
    build:
        uses: ./.github/workflows/build-mod.yml
        with:
            project_name: "ExJojaFarm"
            create_draft_release: true
